# Generated by Django 5.1.7 on 2025-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='star_review',
            field=models.FloatField(default=0),
        ),
    ]
